spring:
  application:
    name: onebuy-ms-product
  datasource:
    url: jdbc:mysql://localhost:3306/onebuy
    username: root
    password: zhanghj811
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/

logging:
  file: logs/onebuy-ms-product.log
