spring:
  application:
    name: onebuy-ms-manage-banked
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/
logging:
  file: logs/onebuy-ms-manage-banked.log